export interface AppItem {
  id: string;
  name: string;
  developer: string;
  rating: number;
  reviews: string;
  price: string;
  category: string;
  icon: string;
  iconBg: string;
  description: string;
  size: string;
  badge?: string;
}

export interface BentoFeaturedApp {
  id: string;
  name: string;
  developer: string;
  rating: number;
  reviews: string;
  price: string;
  category: string;
  banner: string;
  bannerGradient: string;
  description: string;
  icon: string;
}

export const featuredApps: BentoFeaturedApp[] = [
  {
    id: "f1",
    name: "Nova Launcher",
    developer: "TeslaCoil Software",
    rating: 4.5,
    reviews: "12M+",
    price: "Free",
    category: "Personalization",
    banner: "https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?w=600&h=300&fit=crop",
    bannerGradient: "from-emerald-500 via-teal-600 to-cyan-700",
    description: "The most customizable and fast home screen replacement",
    icon: "🚀",
  },
  {
    id: "f2",
    name: "Spotify",
    developer: "Spotify AB",
    rating: 4.3,
    reviews: "48M+",
    price: "Free",
    category: "Music & Audio",
    banner: "https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=600&h=300&fit=crop",
    bannerGradient: "from-green-600 via-green-500 to-lime-400",
    description: "Music for everyone. Podcasts, albums, and more.",
    icon: "🎵",
  },
];

export const categorySections: { title: string; apps: AppItem[] }[] = [
  {
    title: "Recommended for you",
    apps: [
      {
        id: "a1",
        name: "Tasker",
        developer: "Crafty Apps EU",
        rating: 4.3,
        reviews: "612K",
        price: "$3.99",
        category: "Productivity",
        icon: "⚡",
        iconBg: "bg-purple-600",
        description: "Automation for everything",
        size: "14MB",
      },
      {
        id: "a2",
        name: "Threema",
        developer: "Threema GmbH",
        rating: 4.3,
        reviews: "198K",
        price: "$4.99",
        category: "Communication",
        icon: "🔒",
        iconBg: "bg-zinc-900",
        description: "The secure messenger",
        size: "52MB",
      },
      {
        id: "a3",
        name: "Kwai",
        developer: "Joyark Pte. Ltd.",
        rating: 4.4,
        reviews: "18M+",
        price: "Free",
        category: "Entertainment",
        icon: "▶️",
        iconBg: "bg-rose-500",
        description: "Short videos & live streams",
        size: "98MB",
      },
      {
        id: "a4",
        name: "Deep Think AI",
        developer: "MindTech Labs",
        rating: 4.5,
        reviews: "89K",
        price: "Free",
        category: "Productivity",
        icon: "🧠",
        iconBg: "bg-slate-800",
        description: "AI-powered thinking assistant",
        size: "35MB",
      },
      {
        id: "a5",
        name: "StarNote",
        developer: "Star Apps Inc.",
        rating: 4.4,
        reviews: "245K",
        price: "Free",
        category: "Productivity",
        icon: "⭐",
        iconBg: "bg-sky-600",
        description: "Beautiful handwritten notes",
        size: "28MB",
      },
      {
        id: "a6",
        name: "Glass Widgets",
        developer: "Dazzle Apps",
        rating: 4.5,
        reviews: "156K",
        price: "$1.99",
        category: "Personalization",
        icon: "🪟",
        iconBg: "bg-slate-500",
        description: "Elegant modern widgets",
        size: "8MB",
      },
    ],
  },
  {
    title: "Communication",
    apps: [
      {
        id: "b1",
        name: "Telegram",
        developer: "Telegram FZ-LLC",
        rating: 4.1,
        reviews: "98M+",
        price: "Free",
        category: "Communication",
        icon: "✈️",
        iconBg: "bg-sky-500",
        description: "Fast and secure messaging",
        size: "62MB",
      },
      {
        id: "b2",
        name: "Discord",
        developer: "Discord Inc.",
        rating: 4.5,
        reviews: "56M+",
        price: "Free",
        category: "Communication",
        icon: "🎮",
        iconBg: "bg-violet-600",
        description: "Talk, play, hang out",
        size: "115MB",
      },
      {
        id: "b3",
        name: "LINE",
        developer: "LINE Corporation",
        rating: 3.5,
        reviews: "42M+",
        price: "Free",
        category: "Communication",
        icon: "💬",
        iconBg: "bg-green-500",
        description: "Calls & messages, always free",
        size: "210MB",
      },
      {
        id: "b4",
        name: "Zoho Meeting",
        developer: "Zoho Corporation",
        rating: 4.8,
        reviews: "78K",
        price: "Free",
        category: "Communication",
        icon: "📹",
        iconBg: "bg-blue-700",
        description: "Meet virtually, anywhere",
        size: "42MB",
      },
      {
        id: "b5",
        name: "Nicegram",
        developer: "Nicegram Ltd.",
        rating: 4.0,
        reviews: "1.2M",
        price: "Free",
        category: "Communication",
        icon: "✈️",
        iconBg: "bg-zinc-900",
        description: "AI-powered Telegram client",
        size: "55MB",
        badge: "AI",
      },
      {
        id: "b6",
        name: "Signal",
        developer: "Signal Foundation",
        rating: 4.4,
        reviews: "18M+",
        price: "Free",
        category: "Communication",
        icon: "🔔",
        iconBg: "bg-blue-500",
        description: "Private messenger",
        size: "48MB",
      },
    ],
  },
  {
    title: "Top Games",
    apps: [
      {
        id: "c1",
        name: "Genshin Impact",
        developer: "miHoYo",
        rating: 4.4,
        reviews: "15M+",
        price: "Free",
        category: "Games",
        icon: "⚔️",
        iconBg: "bg-amber-600",
        description: "Open-world action RPG",
        size: "350MB",
      },
      {
        id: "c2",
        name: "Stardew Valley",
        developer: "ConcernedApe",
        rating: 4.8,
        reviews: "2.1M",
        price: "$4.99",
        category: "Games",
        icon: "🌾",
        iconBg: "bg-green-700",
        description: "Farm, build, and explore",
        size: "450MB",
      },
      {
        id: "c3",
        name: "Among Us",
        developer: "Innersloth",
        rating: 4.1,
        reviews: "25M+",
        price: "Free",
        category: "Games",
        icon: "🚀",
        iconBg: "bg-red-600",
        description: "Find the imposter",
        size: "290MB",
      },
      {
        id: "c4",
        name: "Monument Valley",
        developer: "ustwo games",
        rating: 4.7,
        reviews: "890K",
        price: "$3.99",
        category: "Games",
        icon: "🏛️",
        iconBg: "bg-pink-400",
        description: "Impossibly beautiful puzzles",
        size: "180MB",
      },
      {
        id: "c5",
        name: "Alto's Odyssey",
        developer: "Team Alto",
        rating: 4.6,
        reviews: "650K",
        price: "Free",
        category: "Games",
        icon: "🏄",
        iconBg: "bg-orange-500",
        description: "Endless sandboarding journey",
        size: "120MB",
      },
      {
        id: "c6",
        name: "Minecraft",
        developer: "Mojang",
        rating: 4.5,
        reviews: "32M+",
        price: "$6.99",
        category: "Games",
        icon: "⛏️",
        iconBg: "bg-stone-600",
        description: "Create, explore, survive",
        size: "500MB",
      },
    ],
  },
  {
    title: "Productivity",
    apps: [
      {
        id: "d1",
        name: "Notion",
        developer: "Notion Labs",
        rating: 4.5,
        reviews: "5.2M",
        price: "Free",
        category: "Productivity",
        icon: "📝",
        iconBg: "bg-zinc-900",
        description: "All-in-one workspace",
        size: "42MB",
      },
      {
        id: "d2",
        name: "Todoist",
        developer: "Doist Inc.",
        rating: 4.4,
        reviews: "3.8M",
        price: "Free",
        category: "Productivity",
        icon: "✅",
        iconBg: "bg-red-500",
        description: "Organize work and life",
        size: "18MB",
      },
      {
        id: "d3",
        name: "1Password",
        developer: "AgileBits",
        rating: 4.6,
        reviews: "520K",
        price: "Free",
        category: "Productivity",
        icon: "🔐",
        iconBg: "bg-sky-700",
        description: "Password manager",
        size: "35MB",
      },
      {
        id: "d4",
        name: "Forest",
        developer: "Seekrtech",
        rating: 4.6,
        reviews: "1.5M",
        price: "$3.99",
        category: "Productivity",
        icon: "🌳",
        iconBg: "bg-green-600",
        description: "Stay focused, be present",
        size: "22MB",
      },
      {
        id: "d5",
        name: "Obsidian",
        developer: "Obsidian",
        rating: 4.7,
        reviews: "320K",
        price: "Free",
        category: "Productivity",
        icon: "💎",
        iconBg: "bg-purple-800",
        description: "A second brain",
        size: "55MB",
      },
      {
        id: "d6",
        name: "CamScanner",
        developer: "IntSig Info",
        rating: 4.3,
        reviews: "8.5M",
        price: "Free",
        category: "Productivity",
        icon: "📄",
        iconBg: "bg-emerald-600",
        description: "Doc scanner & PDF creator",
        size: "75MB",
      },
    ],
  },
];

export const bentoStats = [
  { label: "Apps Available", value: "3.5M+", icon: "📦" },
  { label: "Downloads Today", value: "42M", icon: "⬇️" },
  { label: "Top Rated", value: "4.8★", icon: "🏆" },
  { label: "Editors' Choice", value: "850+", icon: "✨" },
];

export const categories = [
  { name: "Games", icon: "🎮", color: "from-red-500 to-orange-500" },
  { name: "Apps", icon: "📱", color: "from-green-500 to-emerald-500" },
  { name: "Books", icon: "📚", color: "from-amber-500 to-yellow-500" },
  { name: "Kids", icon: "👶", color: "from-pink-500 to-rose-500" },
  { name: "Movies", icon: "🎬", color: "from-purple-500 to-violet-500" },
];
